# Generated by Django 5.2.1 on 2025-06-24 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
