# Generated by Django 5.2.1 on 2025-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joining_date_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
        ),
    ]
