# Generated by Django 5.2.1 on 2025-06-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='slug',
        ),
    ]
